# Generated by Django 4.1.7 on 2023-04-04 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True)),
                ('field_of_study', models.CharField(max_length=250)),
                ('institution', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('latest_experience_one', models.CharField(default='N/A', max_length=255)),
                ('started_experience_one', models.DateField(blank=True)),
                ('ended_experience_one', models.DateField(blank=True)),
                ('latest_experience_one_bio', models.TextField(default='N/A', max_length=500)),
                ('latest_experience_two', models.CharField(default='N/A', max_length=255)),
                ('started_experience_two', models.DateField(blank=True)),
                ('ended_experience_two', models.DateField(blank=True)),
                ('latest_experience_two_bio', models.TextField(default='N/A', max_length=500)),
                ('latest_experience_three', models.CharField(default='N/A', max_length=255)),
                ('started_experience_three', models.DateField(blank=True)),
                ('ended_experience_three', models.DateField(blank=True)),
                ('latest_experience_three_bio', models.TextField(default='N/A', max_length=500)),
                ('profile_photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
