# Generated by Django 4.1.7 on 2023-04-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latest_experience_company_one',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='latest_experience_company_three',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='latest_experience_company_two',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
