# Generated by Django 4.1.7 on 2023-04-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0002_profile_latest_experience_company_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ended_experience_one',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ended_experience_three',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ended_experience_two',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='started_experience_one',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='started_experience_three',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='started_experience_two',
            field=models.DateField(blank=True, null=True),
        ),
    ]
