# Generated by Django 4.1.7 on 2023-04-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0004_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ended_experience_three',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ended_experience_two',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latest_experience_company_three',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latest_experience_company_two',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latest_experience_three',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latest_experience_three_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latest_experience_two',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latest_experience_two_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='started_experience_three',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='started_experience_two',
        ),
    ]
