# Generated by Django 4.1.7 on 2023-04-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0005_remove_profile_ended_experience_three_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='latest_experience_company_one',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ended_experience_one',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='latest_experience_one',
            new_name='last_job',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='started_experience_one',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latest_experience_one_bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
