# Generated by Django 4.2 on 2023-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0006_rename_latest_experience_company_one_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
