# Generated by Django 4.2 on 2023-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0007_alter_profile_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
