# Generated by Django 4.2 on 2023-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0008_alter_profile_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
